"""Add summaries table

Revision ID: 23b07d6368fb
Revises: 51fe08c23591
Create Date: 2025-09-02 23:12:52.389413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b07d6368fb'
down_revision: Union[str, Sequence[str], None] = '51fe08c23591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('ai_model_id', sa.Integer(), nullable=False),
    sa.Column('text_summary_en', sa.String(), nullable=False),
    sa.Column('text_summary_ru', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_ai_model_id'), 'summaries', ['ai_model_id'], unique=False)
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.create_index(op.f('ix_summaries_translation_id'), 'summaries', ['translation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_translation_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_ai_model_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
