"""Rename transcription_status to processing_status

Revision ID: 51fe08c23591
Revises: c04e3c63285b
Create Date: 2025-09-02 23:08:54.249230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51fe08c23591'
down_revision: Union[str, Sequence[str], None] = 'c04e3c63285b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the enum
    op.execute("ALTER TYPE transcription_status RENAME TO processing_status")
    
    op.alter_column('transcriptions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processing_status'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processing_status'),
               existing_nullable=False)
    op.alter_column('translations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processing_status'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processing_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processing_status'),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='transcription_status'),
               existing_nullable=False)
    op.alter_column('transcriptions', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processing_status'),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='transcription_status'),
               existing_nullable=False)
    
    # Rename the enum back
    op.execute("ALTER TYPE processing_status RENAME TO transcription_status")
    # ### end Alembic commands ###
