"""Add translations table

Revision ID: 66cc65808b52
Revises: 19c07edb0398
Create Date: 2025-09-02 23:04:18.067022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cc65808b52'
down_revision: Union[str, Sequence[str], None] = '19c07edb0398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.Column('ai_model_id', sa.Integer(), nullable=False),
    sa.Column('text_translation_en', sa.String(), nullable=False),
    sa.Column('text_translation_ru', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_ai_model_id'), 'translations', ['ai_model_id'], unique=False)
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index(op.f('ix_translations_transcription_id'), 'translations', ['transcription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_transcription_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_ai_model_id'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
