"""Alter transcriptions status to enum

Revision ID: 8abfdf67382e
Revises: f151e399668f
Create Date: 2025-09-02 22:52:51.627255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abfdf67382e'
down_revision: Union[str, Sequence[str], None] = 'f151e399668f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcriptions', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('UPLOADED', 'PROCESSING', 'DONE', 'ERROR', name='status'),
               existing_nullable=False,
               postgresql_using='status::status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcriptions', 'status',
               existing_type=sa.Enum('UPLOADED', 'PROCESSING', 'DONE', 'ERROR', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
