"""Create status enum and update audio_files

Revision ID: 9759e13fc2d9
Revises: 8673059c3f26
Create Date: 2025-09-02 22:30:17.682217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9759e13fc2d9'
down_revision: Union[str, Sequence[str], None] = '8673059c3f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum first
    status_enum = sa.Enum('UPLOADED', 'PROCESSING', 'DONE', 'ERROR', name='status')
    status_enum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('audio_files', 'status',
               existing_type=sa.VARCHAR(),
               type_=status_enum,
               existing_nullable=False,
               postgresql_using='status::status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_files', 'status',
               existing_type=sa.Enum('UPLOADED', 'PROCESSING', 'DONE', 'ERROR', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    # Drop the enum
    status_enum = sa.Enum('UPLOADED', 'PROCESSING', 'DONE', 'ERROR', name='status')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
