"""Add CASCADE DELETE for audio files and SET NULL for user deletion

Revision ID: ae8380670e98
Revises: 734c2cce220c
Create Date: 2025-09-02 23:24:33.252457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8380670e98'
down_revision: Union[str, Sequence[str], None] = '734c2cce220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('audio_files_user_id_fkey'), 'audio_files', type_='foreignkey')
    op.create_foreign_key(None, 'audio_files', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('summaries_translation_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'translations', ['translation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transcriptions_audio_file_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'audio_files', ['audio_file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('translations_transcription_id_fkey'), 'translations', type_='foreignkey')
    op.create_foreign_key(None, 'translations', 'transcriptions', ['transcription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('translations_transcription_id_fkey'), 'translations', type_='foreignkey')
    op.create_foreign_key(op.f('translations_transcription_id_fkey'), 'translations', 'transcriptions', ['transcription_id'], ['id'])
    op.drop_constraint(op.f('transcriptions_audio_file_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptions_audio_file_id_fkey'), 'transcriptions', 'audio_files', ['audio_file_id'], ['id'])
    op.drop_constraint(op.f('summaries_translation_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_translation_id_fkey'), 'summaries', 'translations', ['translation_id'], ['id'])
    op.drop_constraint(op.f('audio_files_user_id_fkey'), 'audio_files', type_='foreignkey')
    op.create_foreign_key(op.f('audio_files_user_id_fkey'), 'audio_files', 'users', ['user_id'], ['id'])
    op.alter_column('audio_files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
