"""Alter translations status to enum

Revision ID: c04e3c63285b
Revises: 66cc65808b52
Create Date: 2025-09-02 23:05:50.001283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04e3c63285b'
down_revision: Union[str, Sequence[str], None] = '66cc65808b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='transcription_status'),
               existing_nullable=False,
               postgresql_using='status::transcription_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='transcription_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
